### ISSUE TITLE
when I run tools/train.py,there is a trackback:RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by sweetboxwwy** [open-mmlab/mmtracking#378]
Traceback (most recent call last):
  File "E:/PycharmProjects/GitHubProjects/mmtracking-master/mmtracking-master/tools/train.py", line 181, in <module>
    main()
  File "E:/PycharmProjects/GitHubProjects/mmtracking-master/mmtracking-master/tools/train.py", line 178, in main
    meta=meta)
  File "E:\PycharmProjects\GitHubProjects\mmtracking-master\mmtracking-master\tools\mmdet\apis\train.py", line 203, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\mmcv\parallel\data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "E:\PycharmProjects\GitHubProjects\mmtracking-master\mmtracking-master\tools\mmdet\models\detectors\base.py", line 248, in train_step
    losses = self(**data)
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\mmcv\runner\fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "E:\PycharmProjects\GitHubProjects\mmtracking-master\mmtracking-master\tools\mmdet\models\detectors\base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "E:\PycharmProjects\GitHubProjects\mmtracking-master\mmtracking-master\tools\mmdet\models\detectors\two_stage.py", line 142, in forward_train
    **kwargs)
  File "E:\PycharmProjects\GitHubProjects\mmtracking-master\mmtracking-master\tools\mmdet\models\dense_heads\base_dense_head.py", line 340, in forward_train
    *outs, img_metas=img_metas, cfg=proposal_cfg)
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\mmcv\runner\fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "E:\PycharmProjects\GitHubProjects\mmtracking-master\mmtracking-master\tools\mmdet\models\dense_heads\base_dense_head.py", line 105, in get_bboxes
    **kwargs)
  File "E:\PycharmProjects\GitHubProjects\mmtracking-master\mmtracking-master\tools\mmdet\models\dense_heads\rpn_head.py", line 187, in _get_bboxes_single
    img_shape)
  File "E:\PycharmProjects\GitHubProjects\mmtracking-master\mmtracking-master\tools\mmdet\models\dense_heads\rpn_head.py", line 231, in _bbox_post_process
    dets, _ = batched_nms(proposals, scores, ids, cfg.nms)
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\mmcv\ops\nms.py", line 307, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\mmcv\utils\misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\mmcv\ops\nms.py", line 172, in nms
    score_threshold, max_num)
  File "C:\Users\wangwy\Anaconda3\lib\site-packages\mmcv\ops\nms.py", line 27, in forward
    bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

and I run python mmdet/utils/collect_env.py is OK!

**Comment by GT9505** [comment]
please use `mmtrack/utils/collect_env.py` to paste the environment information.

**Comment by sweetboxwwy** [comment]
> please use `mmtrack/utils/collect_env.py` to paste the environment information.

thank you~I solved it:

'tail' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'gcc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
fatal: not a git repository (or any of the parent directories): .git
sys.platform: win32
Python: 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3070
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
NVCC: Not Available
GCC: n/a
PyTorch: 1.8.0+cu111
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, 

TorchVision: 0.9.0+cu111
OpenCV: 4.5.4
MMCV: 1.4.1
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 11.1
MMDetection: 2.19.1+

**Comment by zhouzaida** [comment]
Hi @sweetboxwwy , thank you very much for your feedback! We checked our logs and found we missed the compute capability 8_6. We will re-compile and upload the new packages in the next few days.

**Comment by zhouzaida** [comment]
Hi, we have updated the pre-built packages for mmcv-full 1.4.1 and 1.4.2. Please have a try.
